config/routes.rb
Rails.application.routes.draw do
  resources :restaurants, only: [:index, :new, :show, :create] do
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, :address, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, numericality: { only_integer: true }, inclusion: { in: [0, 1, 2, 3, 4, 5] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to @restaurant
    else
      render :new
    end
  end

  def show
    @review = Review.new
  end

  private
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :phone_number, :category)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:index, :new, :create]

  # def index
  #   @reviews = @restaurant.reviews
  # end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    @review.save

    if @restaurant.save
      redirect_to @restaurant
    else
      render :new
    end
  end

  private
  def review_params
      params.require(:review).permit(:content, :rating)
  end

  def set_review
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_navbar.html.erb
<div class="navbar-wagon">

  <%= link_to "Yelp", restaurants_path, class: "navbar-link" %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <%= link_to "Add restaurant", new_restaurant_path, class: "navbar-wagon-item navbar-wagon-link" %>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Add these line for detecting device width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <!-- [...] -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.input :category %>
  </div>

  <div>
    <%= f.submit "Leave your review", { class: "btn btn-primary" } %>
  </div>
<% end %>

app/views/restaurants/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <% @restaurants.each do |restaurant| %>
        <h2><%= link_to restaurant.name, restaurant_path(restaurant.id) %></h2>
          <p><%= restaurant.category.upcase %></p>
          <% restaurant.reviews.first(1).each do |review| %>
            <p><%= review.content.first(150) %></p>
            <p class="star"><%= "★" * review.rating + "☆" * (5 - review.rating) %></p>
            <%= link_to "More", restaurant_path(restaurant.id) %>
          <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/restaurants/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h1>New Restaurant</h1>
        <%= render 'form', restaurant: @restaurant %>
        <hr>
        <%= link_to 'Back', restaurants_path %>
    </div>
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h1><%= @restaurant.name %></h1>
      <p>
        <strong>Address:</strong>
        <%= @restaurant.address %>
      </p>
      <p>
        <strong>Phone:</strong>
        <%= @restaurant.phone_number %>
      </p>
      <p>
        <strong>Category:</strong>
        <%= @restaurant.category %>
      </p>
      <div>
        <p><strong>Reviews:</strong></p>
        <% @restaurant.reviews.each do |review| %>
          <p><%= review.content %></p>
          <p class="star"><%= "★" * review.rating + "☆" * (5 - review.rating) %></p>
        <% end %>
      </div>
      <h1>Leave a review</h1>
        <%= render '/reviews/form', review: @review %>
      <hr>
      <%= link_to 'Back', restaurants_path %>
    </div>
  </div>
</div>

app/views/reviews/_form.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "Leave your review", { class: "btn btn-primary" } %>
<% end %>

app/views/reviews/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h1>New review</h1>
        <%= render 'form', review: @review %>
        <hr>
        <%= link_to 'Back', restaurants_path %>
    </div>
  </div>
</div>